#ifndef BOILER_DEFINITION_H
#define BOILER_DEFINITION_H

typedef enum
{
    BOILER_OK = 0,
    BOILER_ERROR_NULL,
    BOILER_ERROR_DRY_RUN,
    BOILER_ERROR_OVER_TEMP,
    BOILER_ERROR_HIGH_PRESSURE,
    BOILER_ERROR_INVALID_LEVEL
} BoilerStatus;

#endif // BOILER_DEFINITION_H